# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

baseURL = "https://jungleboy.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "jungleboy blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "oeuanalitico"

# Google Analytics
#googleAnalytics = ""

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I'm José"
author = "José Ferraz Neto"
description = "Born in a jungle and living in a world of data."
profilePicture = "/profile.png"
gtagId = "G-3ET97GCNPG"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/netoferraz"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/zeneto"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/joseferrazneto/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:netoferraz@gmail.com"